### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by diskree** [diskree/BACAP-Easy-Setup#1]
## Description

Move the BACAP datapacks configuration realization from https://github.com/diskree/AchieveToDo-BACAP to this separate mod.

## Tasks

- [ ] Core logic of datapacks
- [ ] Settings tab in world creation screen
- [ ] Built-in downloader
- [ ] Protect compatibility on Minecraft migrate
